### ISSUE TITLE
LImiting x axis values to a maximum of 3 decimal places

### ISSUE THREAD

**Issue by kclalit64** [intrepidbird/graphing-calculator#12]
The charts displayed currently have x axis values as more than 20+ decimal places which does not look good at all. It should be better off rounding the decimals to 3 places. Please assign me the issue, I'll work on it.
![Screenshot from 2023-10-28 19-53-24](https://github.com/intrepidbird/graphing-calculator/assets/91486778/87e73ba4-5790-402f-b251-eb6185e1e986)

**Comment by intrepidbird** [comment]
👍

**Comment by kclalit64** [comment]
HI, submitted a PR for an another issue, could you please lmk on it?
