### ISSUE TITLE
No support for exponential operations 

### ISSUE THREAD

**Issue by kclalit64** [intrepidbird/graphing-calculator#13]
the current js code doesn't support operations for exponents within equations. Please assign me this issue so I'll add it.
![Screenshot from 2023-10-28 19-53-24](https://github.com/intrepidbird/graphing-calculator/assets/91486778/695311d1-ae20-476a-b0c3-d6e52dd8fb7d)

**Comment by intrepidbird** [comment]
Yes, exponents are added as x**y.

**Comment by kclalit64** [comment]
Most users use ^ for exponents so may I add that as a posible alternative along with **?

**Comment by intrepidbird** [comment]
Yes 👍
