### ISSUE TITLE
Dark Mode button overlapping with Header at smaller screen size

### ISSUE THREAD

**Issue by AmanSingh81757** [intrepidbird/graphing-calculator#35]
The dark mode button in the header is overlapping with the "Graphing calculator" text in the header.
Screenshot for reference:
![image](https://github.com/intrepidbird/graphing-calculator/assets/102822868/75e83667-5676-4244-bcc3-b8bed878151e)

**Comment by intrepidbird** [comment]
What device are you on?

There's no issue for me.

![image](https://github.com/intrepidbird/graphing-calculator/assets/140008493/23f6d52f-44d3-49cc-93b4-e41a7fc6e0e3)

**Comment by AmanSingh81757** [comment]
Sorry for not mentioning but it is occurring on smaller screen size.
