### ISSUE TITLE
After a Graph is made , we cannot make another graph

### ISSUE THREAD

**Issue by CodeStrate** [intrepidbird/graphing-calculator#6]
#2 Fixes this issue.

- Issue: After you make a graph you cannot make another graph until you destroy or upgrade the Chart.

**Comment by intrepidbird** [comment]
I see, but your PR has conflicts with the main branch. Please resolve these conflicts and then I will accept it 👍

**Comment by CodeStrate** [comment]
@intrepidbird Done.

**Comment by intrepidbird** [comment]
Thanks! 👍
